---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: homeassistant
  labels:
    app: homeassistant
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: homeassistant
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
